name: ci
on:
  push:
    paths-ignore:
      - "docs/**"

env:
  NODE_VERSION: "14"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: Cache
        uses: actions/cache@v2
        with:
          key: "v5-${{ runner.os }}-${{ hashFiles('yarn.lock') }}"
          path: |
            node_modules
            /tmp/.yarn_cache
      - name: Yarn
        run: "yarn --pure-lockfile --cache-folder /tmp/.yarn_cache"
      - name: Lint
        run: 'echo "Linting"'
      - name: Test
        run: 'echo "Testing"'
      - name: Build
        run: 'echo "Building"'
      - id: release
        if: "github.ref == 'refs/heads/main'"
        name: Release
        uses: GoogleCloudPlatform/release-please-action@v2
        with:
          changelog-types: '[{"type":"feat","section":":rocket:  Features"},{"type":"fix","section":":bug:  Bug Fixes"},{"type":"refactor","section":":sunglasses:  Refactor","hidden":true},{"type":"perf","section":":bullettrain_front:  Performance Improvements"},{"type":"docs","section":"Documentation","hidden":false }]'
          package-name: YMNN_
          release-type: node
      - continue-on-error: true
        if: "${{ steps.release.outputs }}"
        name: "Release info"
        run: 'echo "${{ toJSON(steps.release.outputs) }}"'
      - if: "${{ github.ref == 'refs/heads/main' && steps.release.outputs.release_created }}"
        name: Publish
        run: 'echo "Publishing"'
